### ISSUE TITLE
Rollback button does not rollback

### ISSUE THREAD

**Issue by aj-jester** [replicatedhq/kotsadm#1236]
Hello -- The Rollback button in KotsAdm does not seem to perform any action and doesn't actually rollback to the previous release.

Steps to repro:
* Make a deployment with `replicas: 1`.
* Update the deployment with `replicas: 5`.
* After update click the Rollback button, still `replicas: 5`.

Expectation:
* Rollback to `replicas: 1`

**Comment by laverya** [comment]
AJ, we're working on resolving this right now, and it should be fully functional in the next patch. (1.14.2)
