### ISSUE TITLE
After editing config, the version label changes to "Unknown"

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kotsadm#797]
Step to reproduce:

Install a replicated app that has a config spec.
Full out data on the config screen. There's a version label created.
Edit the config, click save.
There's a new version created, but the label is now "Unknown".

**Comment by marccampbell** [comment]
@divolgin I think you addressed this with a different commit after 1.4.0, and it's resolved in 1.4.1? Will you update this issue with additional info or close, as needed?

**Comment by divolgin** [comment]
Yes, PR #174 fixes it.
