### ISSUE TITLE
There is no way to determine the namespace an app is being deployed to

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kotsadm#848]
We should add a `repl{{ Namespace }}` template function or similar in order to allow apps to determine what namespace they are being deployed to. This is used as part of fully qualified service domain names (`<service>.<namespace>.svc.cluster.local`), among other things.

**Comment by MikaelSmith** [comment]
Doesn't this exist? https://kots.io/reference/template-functions/static-context/
