### ISSUE TITLE
Multi-app, GitOps versions behind is off

### ISSUE THREAD

**Issue by grantmiller** [replicatedhq/kotsadm#909]
https://github.com/replicatedhq/kotsadm/blob/235c1f47e16b99e7178bca53e9578dbc83afc0ac/web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx#L29

it seems that after an update or two, the sidebar thinks that the app is perpetually 2 versions behind.

![gitops-behind](https://user-images.githubusercontent.com/1041501/72161243-9a874280-3374-11ea-9380-bbc1ee3ca0c6.png)

**Comment by marccampbell** [comment]
For GitOps enabled apps, we no longer show this message (starting in 1.13.0)
